/**
 * Демо-данные для осмотров CMS Check
 */

import type { Inspection } from '@/types/inspection';
import inspectionService from '@/services/InspectionService';

// Генерация случайной даты в диапазоне
const randomDate = (start: Date, end: Date): Date => {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
};

// Генерация ID для фотографий
const generatePhotoId = (index: number) => `photo-${Date.now()}-${index}`;

// Генерация ID для дефектов
const generateDefectId = (index: number) => `defect-${Date.now()}-${index}`;

// Генерация ID для рекомендаций
const generateRecommendationId = (index: number) => `rec-${Date.now()}-${index}`;

export const generateDemoInspections = (): Omit<Inspection, 'id' | 'createdAt' | 'updatedAt'>[] => {
  const now = new Date();
  const threeMonthsAgo = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
  const oneMonthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
  const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  const inspections: Omit<Inspection, 'id' | 'createdAt' | 'updatedAt'>[] = [
    // 1. Первичный осмотр квартиры
    {
      inspectionType: 'primary',
      status: 'completed',
      inspectionDate: randomDate(threeMonthsAgo, oneMonthAgo),
      scheduledDate: randomDate(threeMonthsAgo, oneMonthAgo),
      completedDate: randomDate(threeMonthsAgo, oneMonthAgo),
      collateralCardId: 'card-1',
      collateralName: '3-комн. квартира, ул. Пушкина, 10-25',
      collateralNumber: 'КО-2024-001',
      address: 'г. Москва, ул. Пушкина, д. 10, кв. 25',
      inspectorId: 'emp-1',
      inspectorName: 'Иванов Иван Иванович',
      inspectorPosition: 'Менеджер по работе с залогами',
      inspectorPhone: '+7 (495) 123-45-67',
      inspectorEmail: 'ivanov@bank.ru',
      condition: 'good',
      overallCondition: 'Квартира в хорошем состоянии, требует косметического ремонта',
      photos: [
        {
          id: generatePhotoId(1),
          url: '/photos/inspection-1-1.jpg',
          thumbnailUrl: '/photos/inspection-1-1-thumb.jpg',
          description: 'Фасад здания',
          takenAt: randomDate(threeMonthsAgo, oneMonthAgo),
          location: 'Фасад',
        },
        {
          id: generatePhotoId(2),
          url: '/photos/inspection-1-2.jpg',
          thumbnailUrl: '/photos/inspection-1-2-thumb.jpg',
          description: 'Гостиная',
          takenAt: randomDate(threeMonthsAgo, oneMonthAgo),
          location: 'Внутри',
        },
      ],
      defects: [
        {
          id: generateDefectId(1),
          description: 'Трещина в стене на кухне',
          severity: 'low',
          location: 'Кухня',
          estimatedCost: 5000,
        },
        {
          id: generateDefectId(2),
          description: 'Износ напольного покрытия в прихожей',
          severity: 'medium',
          location: 'Прихожая',
          estimatedCost: 15000,
        },
      ],
      recommendations: [
        {
          id: generateRecommendationId(1),
          description: 'Провести косметический ремонт',
          priority: 'medium',
          deadline: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000),
        },
      ],
      notes: 'Квартира находится в жилом состоянии, все коммуникации работают',
      weatherConditions: 'Ясно',
      temperature: 22,
      visibility: 'excellent',
      area: 75.5,
      rooms: 3,
      floor: 5,
      totalFloors: 9,
      priority: 'high',
      inspectionCost: 5000,
      duration: 120,
      latitude: 55.7558,
      longitude: 37.6173,
      ownerConsent: true,
      ownerName: 'Петров Петр Петрович',
    },

    // 2. Периодический осмотр офиса
    {
      inspectionType: 'periodic',
      status: 'completed',
      inspectionDate: randomDate(oneMonthAgo, oneWeekAgo),
      scheduledDate: randomDate(oneMonthAgo, oneWeekAgo),
      completedDate: randomDate(oneMonthAgo, oneWeekAgo),
      collateralCardId: 'card-2',
      collateralName: 'Офисное помещение, ул. Ленина, 15',
      collateralNumber: 'КО-2024-002',
      address: 'г. Москва, ул. Ленина, д. 15, оф. 301',
      inspectorId: 'emp-2',
      inspectorName: 'Петрова Мария Сергеевна',
      inspectorPosition: 'Специалист по оценке',
      inspectorPhone: '+7 (495) 123-45-68',
      inspectorEmail: 'petrova@bank.ru',
      condition: 'excellent',
      overallCondition: 'Офисное помещение в отличном состоянии, соответствует классу А',
      photos: [
        {
          id: generatePhotoId(3),
          url: '/photos/inspection-2-1.jpg',
          thumbnailUrl: '/photos/inspection-2-1-thumb.jpg',
          description: 'Вход в офис',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Вход',
        },
      ],
      defects: [],
      recommendations: [
        {
          id: generateRecommendationId(2),
          description: 'Продолжить регулярное обслуживание',
          priority: 'low',
        },
      ],
      notes: 'Помещение полностью соответствует требованиям',
      weatherConditions: 'Облачно',
      temperature: 20,
      visibility: 'good',
      area: 120.0,
      rooms: 1,
      floor: 3,
      totalFloors: 5,
      priority: 'medium',
      inspectionCost: 3000,
      duration: 90,
      latitude: 55.7520,
      longitude: 37.6156,
      ownerConsent: true,
    },

    // 3. Внеплановый осмотр склада
    {
      inspectionType: 'unscheduled',
      status: 'completed',
      inspectionDate: randomDate(oneWeekAgo, now),
      completedDate: randomDate(oneWeekAgo, now),
      collateralCardId: 'card-3',
      collateralName: 'Складское помещение, промзона',
      collateralNumber: 'КО-2024-003',
      address: 'г. Москва, промзона, склад №5',
      inspectorId: 'emp-1',
      inspectorName: 'Иванов Иван Иванович',
      inspectorPosition: 'Менеджер по работе с залогами',
      inspectorPhone: '+7 (495) 123-45-67',
      inspectorEmail: 'ivanov@bank.ru',
      condition: 'satisfactory',
      overallCondition: 'Склад требует ремонта кровли и вентиляции',
      photos: [
        {
          id: generatePhotoId(4),
          url: '/photos/inspection-3-1.jpg',
          thumbnailUrl: '/photos/inspection-3-1-thumb.jpg',
          description: 'Внешний вид склада',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Фасад',
        },
        {
          id: generatePhotoId(5),
          url: '/photos/inspection-3-2.jpg',
          thumbnailUrl: '/photos/inspection-3-2-thumb.jpg',
          description: 'Внутреннее помещение',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Внутри',
        },
      ],
      defects: [
        {
          id: generateDefectId(3),
          description: 'Протечка кровли',
          severity: 'high',
          location: 'Кровля',
          estimatedCost: 50000,
        },
        {
          id: generateDefectId(4),
          description: 'Неисправная вентиляция',
          severity: 'medium',
          location: 'Вентиляционная система',
          estimatedCost: 30000,
        },
      ],
      recommendations: [
        {
          id: generateRecommendationId(3),
          description: 'Срочно провести ремонт кровли',
          priority: 'high',
          deadline: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000),
        },
        {
          id: generateRecommendationId(4),
          description: 'Восстановить систему вентиляции',
          priority: 'medium',
          deadline: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
        },
      ],
      notes: 'Осмотр проведен по жалобе арендатора',
      weatherConditions: 'Дождь',
      temperature: 15,
      visibility: 'good',
      area: 500.0,
      priority: 'high',
      inspectionCost: 8000,
      duration: 180,
      latitude: 55.8000,
      longitude: 37.7000,
      ownerConsent: true,
    },

    // 4. Осмотр после ремонта квартиры
    {
      inspectionType: 'after_repair',
      status: 'completed',
      inspectionDate: randomDate(oneWeekAgo, now),
      scheduledDate: randomDate(oneWeekAgo, now),
      completedDate: randomDate(oneWeekAgo, now),
      collateralCardId: 'card-4',
      collateralName: '2-комн. квартира, ул. Гагарина, 20-10',
      collateralNumber: 'КО-2024-004',
      address: 'г. Москва, ул. Гагарина, д. 20, кв. 10',
      inspectorId: 'emp-2',
      inspectorName: 'Петрова Мария Сергеевна',
      inspectorPosition: 'Специалист по оценке',
      inspectorPhone: '+7 (495) 123-45-68',
      inspectorEmail: 'petrova@bank.ru',
      condition: 'excellent',
      overallCondition: 'Ремонт выполнен качественно, все дефекты устранены',
      photos: [
        {
          id: generatePhotoId(6),
          url: '/photos/inspection-4-1.jpg',
          thumbnailUrl: '/photos/inspection-4-1-thumb.jpg',
          description: 'Кухня после ремонта',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Кухня',
        },
        {
          id: generatePhotoId(7),
          url: '/photos/inspection-4-2.jpg',
          thumbnailUrl: '/photos/inspection-4-2-thumb.jpg',
          description: 'Гостиная после ремонта',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Гостиная',
        },
      ],
      defects: [],
      recommendations: [],
      notes: 'Все работы выполнены согласно смете',
      weatherConditions: 'Ясно',
      temperature: 18,
      visibility: 'excellent',
      area: 55.0,
      rooms: 2,
      floor: 3,
      totalFloors: 5,
      priority: 'medium',
      inspectionCost: 4000,
      duration: 100,
      latitude: 55.7500,
      longitude: 37.6200,
      ownerConsent: true,
      relatedInspectionIds: ['insp-1'],
    },

    // 5. Осмотр перед выдачей кредита (автомобиль)
    {
      inspectionType: 'before_loan',
      status: 'completed',
      inspectionDate: randomDate(oneMonthAgo, oneWeekAgo),
      scheduledDate: randomDate(oneMonthAgo, oneWeekAgo),
      completedDate: randomDate(oneMonthAgo, oneWeekAgo),
      collateralCardId: 'card-5',
      collateralName: 'Toyota Camry 2020',
      collateralNumber: 'КО-2024-005',
      address: 'г. Москва, автосалон "Тойота Центр"',
      inspectorId: 'emp-3',
      inspectorName: 'Сидоров Алексей Владимирович',
      inspectorPosition: 'Менеджер по работе с залогами',
      inspectorPhone: '+7 (812) 234-56-78',
      inspectorEmail: 'sidorov@bank.ru',
      condition: 'excellent',
      overallCondition: 'Автомобиль в отличном состоянии, соответствует заявленным характеристикам',
      photos: [
        {
          id: generatePhotoId(8),
          url: '/photos/inspection-5-1.jpg',
          thumbnailUrl: '/photos/inspection-5-1-thumb.jpg',
          description: 'Внешний вид автомобиля',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Фасад',
        },
        {
          id: generatePhotoId(9),
          url: '/photos/inspection-5-2.jpg',
          thumbnailUrl: '/photos/inspection-5-2-thumb.jpg',
          description: 'Салон',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Внутри',
        },
        {
          id: generatePhotoId(10),
          url: '/photos/inspection-5-3.jpg',
          thumbnailUrl: '/photos/inspection-5-3-thumb.jpg',
          description: 'Двигатель',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Двигатель',
        },
      ],
      defects: [],
      recommendations: [],
      notes: 'Автомобиль проверен, все системы работают',
      weatherConditions: 'Ясно',
      temperature: 20,
      visibility: 'excellent',
      mileage: 25000,
      vin: 'JT2BF28K904012345',
      licensePlate: 'А123БВ777',
      priority: 'high',
      inspectionCost: 6000,
      duration: 150,
      latitude: 55.7600,
      longitude: 37.6100,
      ownerConsent: true,
    },

    // 6. Осмотр при переоценке (торговое помещение)
    {
      inspectionType: 'revaluation',
      status: 'completed',
      inspectionDate: randomDate(oneMonthAgo, oneWeekAgo),
      scheduledDate: randomDate(oneMonthAgo, oneWeekAgo),
      completedDate: randomDate(oneMonthAgo, oneWeekAgo),
      collateralCardId: 'card-6',
      collateralName: 'Торговое помещение, ТЦ "Мега"',
      collateralNumber: 'КО-2024-006',
      address: 'г. Москва, ТЦ "Мега", 1-й этаж, павильон 15',
      inspectorId: 'emp-2',
      inspectorName: 'Петрова Мария Сергеевна',
      inspectorPosition: 'Специалист по оценке',
      inspectorPhone: '+7 (495) 123-45-68',
      inspectorEmail: 'petrova@bank.ru',
      condition: 'good',
      overallCondition: 'Помещение в хорошем состоянии, требуется обновление витрины',
      photos: [
        {
          id: generatePhotoId(11),
          url: '/photos/inspection-6-1.jpg',
          thumbnailUrl: '/photos/inspection-6-1-thumb.jpg',
          description: 'Витрина',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Витрина',
        },
      ],
      defects: [
        {
          id: generateDefectId(5),
          description: 'Износ витрины',
          severity: 'low',
          location: 'Витрина',
          estimatedCost: 20000,
        },
      ],
      recommendations: [
        {
          id: generateRecommendationId(5),
          description: 'Обновить витрину',
          priority: 'low',
        },
      ],
      notes: 'Помещение пригодно для торговли',
      weatherConditions: 'Ясно',
      temperature: 22,
      visibility: 'excellent',
      area: 80.0,
      floor: 1,
      totalFloors: 3,
      priority: 'medium',
      inspectionCost: 5000,
      duration: 90,
      latitude: 55.7700,
      longitude: 37.6000,
      ownerConsent: true,
    },

    // 7. Осмотр при передаче (жилой дом)
    {
      inspectionType: 'transfer',
      status: 'completed',
      inspectionDate: randomDate(oneWeekAgo, now),
      scheduledDate: randomDate(oneWeekAgo, now),
      completedDate: randomDate(oneWeekAgo, now),
      collateralCardId: 'card-7',
      collateralName: 'Жилой дом, ул. Садовая, 5',
      collateralNumber: 'КО-2024-007',
      address: 'г. Москва, ул. Садовая, д. 5',
      inspectorId: 'emp-1',
      inspectorName: 'Иванов Иван Иванович',
      inspectorPosition: 'Менеджер по работе с залогами',
      inspectorPhone: '+7 (495) 123-45-67',
      inspectorEmail: 'ivanov@bank.ru',
      condition: 'satisfactory',
      overallCondition: 'Дом требует капитального ремонта',
      photos: [
        {
          id: generatePhotoId(12),
          url: '/photos/inspection-7-1.jpg',
          thumbnailUrl: '/photos/inspection-7-1-thumb.jpg',
          description: 'Фасад дома',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Фасад',
        },
        {
          id: generatePhotoId(13),
          url: '/photos/inspection-7-2.jpg',
          thumbnailUrl: '/photos/inspection-7-2-thumb.jpg',
          description: 'Внутренние помещения',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Внутри',
        },
      ],
      defects: [
        {
          id: generateDefectId(6),
          description: 'Трещины в фундаменте',
          severity: 'critical',
          location: 'Фундамент',
          estimatedCost: 200000,
        },
        {
          id: generateDefectId(7),
          description: 'Протечка кровли',
          severity: 'high',
          location: 'Кровля',
          estimatedCost: 80000,
        },
      ],
      recommendations: [
        {
          id: generateRecommendationId(6),
          description: 'Провести капитальный ремонт',
          priority: 'high',
          deadline: new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000),
        },
      ],
      notes: 'Дом передан новому владельцу',
      weatherConditions: 'Облачно',
      temperature: 16,
      visibility: 'good',
      area: 150.0,
      rooms: 5,
      floor: 2,
      totalFloors: 2,
      priority: 'high',
      inspectionCost: 10000,
      duration: 240,
      latitude: 55.7400,
      longitude: 37.6300,
      ownerConsent: true,
    },

    // 8. Осмотр при списании (оборудование)
    {
      inspectionType: 'write_off',
      status: 'completed',
      inspectionDate: randomDate(oneWeekAgo, now),
      scheduledDate: randomDate(oneWeekAgo, now),
      completedDate: randomDate(oneWeekAgo, now),
      collateralCardId: 'card-8',
      collateralName: 'Производственное оборудование',
      collateralNumber: 'КО-2024-008',
      address: 'г. Москва, промзона, цех №3',
      inspectorId: 'emp-3',
      inspectorName: 'Сидоров Алексей Владимирович',
      inspectorPosition: 'Менеджер по работе с залогами',
      inspectorPhone: '+7 (812) 234-56-78',
      inspectorEmail: 'sidorov@bank.ru',
      condition: 'poor',
      overallCondition: 'Оборудование полностью изношено, подлежит списанию',
      photos: [
        {
          id: generatePhotoId(14),
          url: '/photos/inspection-8-1.jpg',
          thumbnailUrl: '/photos/inspection-8-1-thumb.jpg',
          description: 'Общий вид оборудования',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Общий вид',
        },
      ],
      defects: [
        {
          id: generateDefectId(8),
          description: 'Полный износ основных узлов',
          severity: 'critical',
          location: 'Основные узлы',
        },
        {
          id: generateDefectId(9),
          description: 'Коррозия корпуса',
          severity: 'high',
          location: 'Корпус',
        },
      ],
      recommendations: [
        {
          id: generateRecommendationId(7),
          description: 'Списать оборудование',
          priority: 'high',
          completed: true,
          completedDate: new Date(),
        },
      ],
      notes: 'Оборудование не подлежит восстановлению',
      weatherConditions: 'Ясно',
      temperature: 18,
      visibility: 'excellent',
      priority: 'medium',
      inspectionCost: 3000,
      duration: 60,
      latitude: 55.8000,
      longitude: 37.7000,
      ownerConsent: true,
    },

    // 9. Осмотр при продаже (квартира)
    {
      inspectionType: 'sale',
      status: 'completed',
      inspectionDate: randomDate(oneWeekAgo, now),
      scheduledDate: randomDate(oneWeekAgo, now),
      completedDate: randomDate(oneWeekAgo, now),
      collateralCardId: 'card-9',
      collateralName: '1-комн. квартира, ул. Мира, 30-12',
      collateralNumber: 'КО-2024-009',
      address: 'г. Москва, ул. Мира, д. 30, кв. 12',
      inspectorId: 'emp-2',
      inspectorName: 'Петрова Мария Сергеевна',
      inspectorPosition: 'Специалист по оценке',
      inspectorPhone: '+7 (495) 123-45-68',
      inspectorEmail: 'petrova@bank.ru',
      condition: 'good',
      overallCondition: 'Квартира готова к продаже',
      photos: [
        {
          id: generatePhotoId(15),
          url: '/photos/inspection-9-1.jpg',
          thumbnailUrl: '/photos/inspection-9-1-thumb.jpg',
          description: 'Гостиная',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Гостиная',
        },
        {
          id: generatePhotoId(16),
          url: '/photos/inspection-9-2.jpg',
          thumbnailUrl: '/photos/inspection-9-2-thumb.jpg',
          description: 'Кухня',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Кухня',
        },
      ],
      defects: [
        {
          id: generateDefectId(10),
          description: 'Небольшие царапины на полу',
          severity: 'low',
          location: 'Пол',
          estimatedCost: 3000,
        },
      ],
      recommendations: [],
      notes: 'Квартира в хорошем состоянии',
      weatherConditions: 'Ясно',
      temperature: 20,
      visibility: 'excellent',
      area: 35.0,
      rooms: 1,
      floor: 2,
      totalFloors: 5,
      priority: 'high',
      inspectionCost: 4000,
      duration: 90,
      latitude: 55.7800,
      longitude: 37.6400,
      ownerConsent: true,
    },

    // 10. Осмотр при аварии (автомобиль)
    {
      inspectionType: 'accident',
      status: 'completed',
      inspectionDate: randomDate(oneWeekAgo, now),
      completedDate: randomDate(oneWeekAgo, now),
      collateralCardId: 'card-10',
      collateralName: 'BMW X5 2019',
      collateralNumber: 'КО-2024-010',
      address: 'г. Москва, СТО "Автосервис"',
      inspectorId: 'emp-3',
      inspectorName: 'Сидоров Алексей Владимирович',
      inspectorPosition: 'Менеджер по работе с залогами',
      inspectorPhone: '+7 (812) 234-56-78',
      inspectorEmail: 'sidorov@bank.ru',
      condition: 'poor',
      overallCondition: 'Автомобиль поврежден в результате ДТП, требуется ремонт',
      photos: [
        {
          id: generatePhotoId(17),
          url: '/photos/inspection-10-1.jpg',
          thumbnailUrl: '/photos/inspection-10-1-thumb.jpg',
          description: 'Поврежденный бампер',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Передняя часть',
        },
        {
          id: generatePhotoId(18),
          url: '/photos/inspection-10-2.jpg',
          thumbnailUrl: '/photos/inspection-10-2-thumb.jpg',
          description: 'Поврежденная дверь',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Боковая часть',
        },
      ],
      defects: [
        {
          id: generateDefectId(11),
          description: 'Поврежден передний бампер',
          severity: 'high',
          location: 'Передний бампер',
          estimatedCost: 150000,
        },
        {
          id: generateDefectId(12),
          description: 'Вмятина на левой двери',
          severity: 'medium',
          location: 'Левая дверь',
          estimatedCost: 50000,
        },
      ],
      recommendations: [
        {
          id: generateRecommendationId(8),
          description: 'Провести ремонт в авторизованном сервисе',
          priority: 'high',
          deadline: new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000),
        },
      ],
      notes: 'ДТП произошло 15.11.2024, автомобиль на ремонте',
      weatherConditions: 'Дождь',
      temperature: 5,
      visibility: 'poor',
      mileage: 45000,
      vin: 'WBAFR9C59ED123456',
      licensePlate: 'В456ГД777',
      priority: 'high',
      inspectionCost: 8000,
      duration: 120,
      latitude: 55.7500,
      longitude: 37.6500,
      ownerConsent: true,
    },

    // 11. Осмотр при жалобе (офис)
    {
      inspectionType: 'complaint',
      status: 'completed',
      inspectionDate: randomDate(oneWeekAgo, now),
      completedDate: randomDate(oneWeekAgo, now),
      collateralCardId: 'card-11',
      collateralName: 'Офисное помещение, ул. Тверская, 10',
      collateralNumber: 'КО-2024-011',
      address: 'г. Москва, ул. Тверская, д. 10, оф. 205',
      inspectorId: 'emp-1',
      inspectorName: 'Иванов Иван Иванович',
      inspectorPosition: 'Менеджер по работе с залогами',
      inspectorPhone: '+7 (495) 123-45-67',
      inspectorEmail: 'ivanov@bank.ru',
      condition: 'satisfactory',
      overallCondition: 'Выявлены проблемы с отоплением, требуется ремонт',
      photos: [
        {
          id: generatePhotoId(19),
          url: '/photos/inspection-11-1.jpg',
          thumbnailUrl: '/photos/inspection-11-1-thumb.jpg',
          description: 'Радиатор отопления',
          takenAt: randomDate(oneWeekAgo, now),
          location: 'Отопление',
        },
      ],
      defects: [
        {
          id: generateDefectId(13),
          description: 'Не работает отопление',
          severity: 'high',
          location: 'Система отопления',
          estimatedCost: 25000,
        },
      ],
      recommendations: [
        {
          id: generateRecommendationId(9),
          description: 'Срочно восстановить отопление',
          priority: 'high',
          deadline: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
        },
      ],
      notes: 'Жалоба от арендатора на отсутствие отопления',
      weatherConditions: 'Холодно',
      temperature: -5,
      visibility: 'good',
      area: 90.0,
      rooms: 1,
      floor: 2,
      totalFloors: 6,
      priority: 'high',
      inspectionCost: 4000,
      duration: 60,
      latitude: 55.7558,
      longitude: 37.6173,
      ownerConsent: true,
    },

    // 12. Осмотр при инвентаризации (склад)
    {
      inspectionType: 'inventory',
      status: 'completed',
      inspectionDate: randomDate(oneMonthAgo, oneWeekAgo),
      scheduledDate: randomDate(oneMonthAgo, oneWeekAgo),
      completedDate: randomDate(oneMonthAgo, oneWeekAgo),
      collateralCardId: 'card-12',
      collateralName: 'Складское помещение, промзона №2',
      collateralNumber: 'КО-2024-012',
      address: 'г. Москва, промзона, склад №2',
      inspectorId: 'emp-4',
      inspectorName: 'Козлова Елена Александровна',
      inspectorPosition: 'Специалист по мониторингу',
      inspectorPhone: '+7 (383) 345-67-89',
      inspectorEmail: 'kozlova@bank.ru',
      condition: 'good',
      overallCondition: 'Склад соответствует инвентаризационным данным',
      photos: [
        {
          id: generatePhotoId(20),
          url: '/photos/inspection-12-1.jpg',
          thumbnailUrl: '/photos/inspection-12-1-thumb.jpg',
          description: 'Общий вид склада',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Общий вид',
        },
      ],
      defects: [],
      recommendations: [],
      notes: 'Инвентаризация проведена, все соответствует',
      weatherConditions: 'Ясно',
      temperature: 12,
      visibility: 'excellent',
      area: 300.0,
      priority: 'medium',
      inspectionCost: 6000,
      duration: 180,
      latitude: 55.8000,
      longitude: 37.7000,
      ownerConsent: true,
    },

    // 13. Осмотр при проверке (гостиница)
    {
      inspectionType: 'audit',
      status: 'completed',
      inspectionDate: randomDate(oneMonthAgo, oneWeekAgo),
      scheduledDate: randomDate(oneMonthAgo, oneWeekAgo),
      completedDate: randomDate(oneMonthAgo, oneWeekAgo),
      collateralCardId: 'card-13',
      collateralName: 'Гостиница "Восток"',
      collateralNumber: 'КО-2024-013',
      address: 'г. Москва, ул. Гостиничная, д. 1',
      inspectorId: 'emp-2',
      inspectorName: 'Петрова Мария Сергеевна',
      inspectorPosition: 'Специалист по оценке',
      inspectorPhone: '+7 (495) 123-45-68',
      inspectorEmail: 'petrova@bank.ru',
      condition: 'good',
      overallCondition: 'Гостиница соответствует стандартам',
      photos: [
        {
          id: generatePhotoId(21),
          url: '/photos/inspection-13-1.jpg',
          thumbnailUrl: '/photos/inspection-13-1-thumb.jpg',
          description: 'Фасад гостиницы',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Фасад',
        },
        {
          id: generatePhotoId(22),
          url: '/photos/inspection-13-2.jpg',
          thumbnailUrl: '/photos/inspection-13-2-thumb.jpg',
          description: 'Номер',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Номер',
        },
      ],
      defects: [
        {
          id: generateDefectId(14),
          description: 'Требуется обновление мебели в некоторых номерах',
          severity: 'low',
          location: 'Номера',
          estimatedCost: 100000,
        },
      ],
      recommendations: [
        {
          id: generateRecommendationId(10),
          description: 'Постепенно обновить мебель',
          priority: 'low',
        },
      ],
      notes: 'Проверка соответствия стандартам гостиничного сервиса',
      weatherConditions: 'Ясно',
      temperature: 18,
      visibility: 'excellent',
      area: 2000.0,
      rooms: 50,
      floor: 5,
      totalFloors: 5,
      priority: 'medium',
      inspectionCost: 15000,
      duration: 300,
      latitude: 55.7600,
      longitude: 37.6200,
      ownerConsent: true,
    },

    // 14. Осмотр при мониторинге (земельный участок)
    {
      inspectionType: 'monitoring',
      status: 'completed',
      inspectionDate: randomDate(oneMonthAgo, oneWeekAgo),
      scheduledDate: randomDate(oneMonthAgo, oneWeekAgo),
      completedDate: randomDate(oneMonthAgo, oneWeekAgo),
      collateralCardId: 'card-14',
      collateralName: 'Земельный участок, МО, 15 соток',
      collateralNumber: 'КО-2024-014',
      address: 'Московская область, участок №45',
      inspectorId: 'emp-4',
      inspectorName: 'Козлова Елена Александровна',
      inspectorPosition: 'Специалист по мониторингу',
      inspectorPhone: '+7 (383) 345-67-89',
      inspectorEmail: 'kozlova@bank.ru',
      condition: 'good',
      overallCondition: 'Участок в хорошем состоянии, границы сохранены',
      photos: [
        {
          id: generatePhotoId(23),
          url: '/photos/inspection-14-1.jpg',
          thumbnailUrl: '/photos/inspection-14-1-thumb.jpg',
          description: 'Общий вид участка',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Общий вид',
        },
        {
          id: generatePhotoId(24),
          url: '/photos/inspection-14-2.jpg',
          thumbnailUrl: '/photos/inspection-14-2-thumb.jpg',
          description: 'Границы участка',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Границы',
        },
      ],
      defects: [],
      recommendations: [],
      notes: 'Регулярный мониторинг участка',
      weatherConditions: 'Ясно',
      temperature: 15,
      visibility: 'excellent',
      area: 1500, // в кв.м (15 соток)
      priority: 'low',
      inspectionCost: 5000,
      duration: 120,
      latitude: 55.9000,
      longitude: 37.8000,
      ownerConsent: true,
    },

    // 15. Осмотр при оценке (промышленное здание)
    {
      inspectionType: 'appraisal',
      status: 'completed',
      inspectionDate: randomDate(oneMonthAgo, oneWeekAgo),
      scheduledDate: randomDate(oneMonthAgo, oneWeekAgo),
      completedDate: randomDate(oneMonthAgo, oneWeekAgo),
      collateralCardId: 'card-15',
      collateralName: 'Промышленное здание, цех №1',
      collateralNumber: 'КО-2024-015',
      address: 'г. Москва, промзона, цех №1',
      inspectorId: 'emp-2',
      inspectorName: 'Петрова Мария Сергеевна',
      inspectorPosition: 'Специалист по оценке',
      inspectorPhone: '+7 (495) 123-45-68',
      inspectorEmail: 'petrova@bank.ru',
      condition: 'satisfactory',
      overallCondition: 'Здание требует капитального ремонта, но пригодно для эксплуатации',
      photos: [
        {
          id: generatePhotoId(25),
          url: '/photos/inspection-15-1.jpg',
          thumbnailUrl: '/photos/inspection-15-1-thumb.jpg',
          description: 'Фасад здания',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Фасад',
        },
        {
          id: generatePhotoId(26),
          url: '/photos/inspection-15-2.jpg',
          thumbnailUrl: '/photos/inspection-15-2-thumb.jpg',
          description: 'Внутренние помещения',
          takenAt: randomDate(oneMonthAgo, oneWeekAgo),
          location: 'Внутри',
        },
      ],
      defects: [
        {
          id: generateDefectId(15),
          description: 'Трещины в стенах',
          severity: 'medium',
          location: 'Стены',
          estimatedCost: 150000,
        },
        {
          id: generateDefectId(16),
          description: 'Износ кровли',
          severity: 'medium',
          location: 'Кровля',
          estimatedCost: 200000,
        },
      ],
      recommendations: [
        {
          id: generateRecommendationId(11),
          description: 'Провести капитальный ремонт в течение года',
          priority: 'medium',
          deadline: new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000),
        },
      ],
      notes: 'Осмотр для оценки стоимости объекта',
      weatherConditions: 'Облачно',
      temperature: 10,
      visibility: 'good',
      area: 800.0,
      floor: 1,
      totalFloors: 1,
      priority: 'medium',
      inspectionCost: 12000,
      duration: 240,
      latitude: 55.8000,
      longitude: 37.7000,
      ownerConsent: true,
    },
  ];

  return inspections;
};

/**
 * Загрузить демо-данные осмотров в базу данных
 */
export const loadInspectionDemoData = async (): Promise<void> => {
  try {
    await inspectionService.initDatabase();
    const inspections = generateDemoInspections();
    
    for (const inspection of inspections) {
      await inspectionService.createInspection(inspection);
    }
    
    console.log(`✅ Загружено ${inspections.length} демо-осмотров`);
  } catch (error) {
    console.error('Ошибка загрузки демо-данных осмотров:', error);
    throw error;
  }
};

